### ISSUE TITLE
Should this be closed, as core includes this functionality already?

### ISSUE THREAD

**Issue by deiga** [lexicalunit/no-title-bar#16]
https://github.com/atom/atom/pull/13616

**Comment by lexicalunit** [comment]
Thank you for your interest in this package. The `no-title-bar` package provides more features than are offered by the now core title bar customizations built into Atom. In fact, this package has been updated to support these new options.

Benefits of using `no-title-bar` over the `hidden` title bar setting:

1. You don't lose the window's traffic lights.
2. You don't lose the ability to manipulate the window position using the mouse.
3. You have the option of enabling an alternative click and drag mode for the tab bar.

Even if you decide to use the core `hidden` title bar setting you will gain benefits 2 and 3 if you have `no-title-bar` installed and enabled.
