### ISSUE TITLE
Unable to drag window

### ISSUE THREAD

**Issue by macgyver** [lexicalunit/no-title-bar#18]
Hey there, I know you specifically state that drag/drop should work if you just grab the empty space, but it's not working on my system. I'm using the `custom` Title bar option from the core settings. I've tried dragging by clicking and dragging and also with three-finger drag and neither work. Can I provide any more info to help debug it?

**Comment by lexicalunit** [comment]
Sorry you're having issues with the package @macgyver! The approach I took for enabling dragging was to enable it over the entire application, then specifically disable it for certain regions. For example inside the text editor itself you wouldn't want it to drag the window because then you'd be unable to select text with the mouse. Other areas that you can't drag the window from include:

- Docks
- Linter Panels
- Settings Views
- Resize Handles

Could you describe the element you're mouse is over when you are trying to drag the window? Even better would be a screenshot of the area!

**Comment by macgyver** [comment]
I'm trying the top area between the tabs and the traffic light: 
![fullscreen_5_24_17__3_53_pm](https://cloud.githubusercontent.com/assets/1163/26422792/39e88324-4099-11e7-99b2-3d34a9a34eff.png)

**Comment by lexicalunit** [comment]
Yep that should totally work! I wonder what's going on here... hrmmmm...

Let me try recreating it using the same theme that you're using. What theme is that?

**Comment by macgyver** [comment]
It's One Dark / One Dark, and here's my installed packages:
```
$ apm ls
Built-in Atom Packages (90)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.3
├── one-light-ui@1.10.3
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.6
├── archive-view@0.63.2
├── autocomplete-atom-api@0.10.1
├── autocomplete-css@0.16.1
├── autocomplete-html@0.7.3
├── autocomplete-plus@2.35.3
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.2
├── background-tips@0.27.0
├── bookmarks@0.44.3
├── bracket-matcher@0.85.5
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.3
├── exception-reporting@0.41.3
├── find-and-replace@0.207.6
├── fuzzy-finder@1.5.6
├── git-diff@1.3.5
├── go-to-line@0.32.0
├── grammar-selector@0.49.4
├── image-view@0.61.2
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.6.3
├── link@0.31.3
├── markdown-preview@0.159.11
├── metrics@1.2.3
├── notifications@0.67.1
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.249.4
├── snippets@1.1.4
├── spell-check@0.71.4
├── status-bar@1.8.7
├── styleguide@0.49.6
├── symbols-view@0.115.5
├── tabs@0.106.0
├── timecop@0.36.0
├── tree-view@0.217.0-7
├── update-package-dependencies@0.11.0
├── welcome@0.36.2
├── whitespace@0.36.2
├── wrap-guide@0.40.1
├── language-c@0.57.0
├── language-clojure@0.22.2
├── language-coffee-script@0.48.6
├── language-csharp@0.14.2
├── language-css@0.42.2
├── language-gfm@0.88.1
├── language-git@0.19.0
├── language-go@0.43.1
├── language-html@0.47.2
├── language-hyperlink@0.16.1
├── language-java@0.27.0
├── language-javascript@0.126.1
├── language-json@0.19.0
├── language-less@0.32.0
├── language-make@0.22.3
├── language-mustache@0.13.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.38.0
├── language-property-list@0.9.1
├── language-python@0.45.2
├── language-ruby@0.71.0
├── language-ruby-on-rails@0.25.2
├── language-sass@0.59.0
├── language-shellscript@0.25.0
├── language-source@0.9.0
├── language-sql@0.25.4
├── language-text@0.7.2
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.35.0
└── language-yaml@0.29.0

Community Packages (50) /Users/jz/.atom/packages
├── AtomicFreckle@0.2.0
├── activate-power-mode@1.4.0
├── an-old-hope-syntax@1.0.4
├── atom-monokai@0.10.9
├── atom-ternjs@0.18.3
├── busy-signal@1.4.1
├── color-picker@2.2.5
├── dudeness-syntax@0.1.0
├── duotone-dark-earth-syntax@2.1.0
├── duotone-dark-forest-syntax@2.1.0
├── duotone-dark-sea-syntax@2.1.0
├── duotone-dark-space-syntax@2.1.0
├── duotone-dark-syntax@2.1.0
├── editorconfig@2.2.2
├── ex-mode@0.14.0
├── file-icons@2.1.6
├── filter-syntax@0.3.0
├── fizzy@0.21.0
├── highlight-selected@0.13.1
├── hyperclick@0.0.40
├── intentions@1.1.2
├── js-hyperclick@1.11.0
├── jsformat@0.9.3
├── language-babel@2.62.0
├── language-javascript-jsx@0.3.7
├── last-tab@0.1.6
├── linter@2.1.4
├── linter-coffeescript@1.0.0
├── linter-csslint@1.3.4
├── linter-eslint@8.2.1
├── linter-flake8@2.2.1
├── linter-sass-lint@1.7.4
├── linter-scss-lint@3.1.0
├── linter-stylelint
├── linter-ui-default@1.6.0
├── merge-conflicts@1.4.5
├── minimap@4.28.2
├── multi-cursor@2.1.5
├── no-title-bar@0.6.6
├── node-debugger@1.10.1
├── octocat-syntax@1.3.1
├── pigments@0.39.1
├── pretty-json@1.6.3
├── python-tools@0.6.9
├── react@0.16.2
├── spectrum-light-syntax@0.0.5
├── stylefmt@4.1.1
├── tablr@1.8.3
├── uglify@1.3.1
└── vim-mode@0.66.0
```

**Comment by lexicalunit** [comment]
Ty! Sadly I'm having trouble recreating the issue you're facing. I'm able to drag the window in the empty space both before and after the tabs when I have the One-Dark activated.

One thing I've noticed is that window dragging doesn't work when you have the debug panel open. Though I don't see that it's open in your screen shot so that's probably not the problem here. And even if you had the debug panel in another window, that would only affect that window. Not other Atom windows.

Question: Are you able to drag and drop re-arrange the tabs in the tab bar?

**Comment by macgyver** [comment]
Yep, I can re-arrange tabs.

**Comment by jbergstroem** [comment]
I've actually run into this once or twice too. For me I think its related to manually hiding the 'project' tab from file-tree though.

**Comment by lexicalunit** [comment]
It's possible the meta key drag feature was causing some issues. Sadly (happily?) that feature no longer works so I ripped it out of version 1.0.0 of the package. I'll close this ticket for now on the assumption that the latest version is working as I still can't re-create this issue and have never been able to. But please, anyone who is experiencing this issue, feel free to re-open with more information :)

**Comment by macgyver** [comment]
Just curious, when do you plan to release 1.0.0? 0.6.6 seems like the most recent version on `apm`

**Comment by macgyver** [comment]
oh, correction.. `apm` shows version 1.2.1... but the visual package manager in Atom seems to think 0.6.6 is the latest version... any idea why there is a disparity?

**Comment by macgyver** [comment]
oh, the answer is here:
<img width="619" alt="screen shot 2017-07-02 at 5 04 08 pm" src="https://user-images.githubusercontent.com/1163/27773474-864ad050-5f48-11e7-9301-883269337df5.png">

I guess I'll just wait for whichever version of Atom unblocks me from installing the latest of your package

**Comment by macgyver** [comment]
oh here's something slightly interesting - I noticed that when I grab to the right of the tab menu, dragging *does* work, but when I grab to the left of it (above the projects tab in the tree view of the files) that's where it does not work, it's the orange margin area in this screenshot that is the problem:

![fullscreen_7_3_17__10_58_am](https://user-images.githubusercontent.com/1163/27798285-b3bfe778-5fde-11e7-9ffc-b2ad943ce343.png)


I'll probably update this ticket again whenever ~1.0.0 becomes available for the stable release of Atom ;)

**Comment by lexicalunit** [comment]
Ahhhh yeah... I bet that's due to a bug that was fixed after v1.0.0 which will be out for Atom 1.19.0. Thanks for keeping track @macgyver. I'll reopen this for now and close if it appears to be fixed when Atom 1.19.0 releases.

**Comment by macgyver** [comment]
Fwiw, I'm on 1.19.0 of Atom and 1.4.1 of `no-title-bar` and the issue persists

**Comment by lexicalunit** [comment]
@macgyver do you have anything configured in your Atom `styles.less` that could be affecting things?

**Comment by macgyver** [comment]
Nope, the only I've added is this: 
```less
.tab-bar .tab:not(.active) {
  opacity: 0.6;
}
```

**Comment by macgyver** [comment]
wait, holy cow - it just started working....

**Comment by lexicalunit** [comment]
🔮 Hurrah, my magical incantation worked! 🔮

Seriously tho, I wish I knew what the issue was so I could ensure it doesn't crop up again.

**Comment by lexicalunit** [comment]
Closing for now...

**Comment by macgyver** [comment]
Thanks for holding my hand through this ;) I really can't explain what finally did the trick - I had the dev tools open and I was fiddling with the style sheet, and somewhere along the way some cache must've gotten flushed and it started working.
