### ISSUE TITLE
Traffic lights text overflow

### ISSUE THREAD

**Issue by jbergstroem** [lexicalunit/no-title-bar#19]
If the tab menu is too cluttered, it seems to overflow. Not sure if related to having the preview open, but here we are:
<img width="778" alt="screen shot 2017-05-26 at 5 10 39 pm" src="https://cloud.githubusercontent.com/assets/176984/26512802/4378362a-4236-11e7-9ec8-f3baf43ad849.png">

**Comment by lexicalunit** [comment]
Yeah, this is [the issue I discovered](https://github.com/lexicalunit/no-title-bar/issues/17#issuecomment-302124923) while debugging #17. Sadly I haven't had time to look into how to fix it yet. Ty for creating a separate issue for tracking this!

**Comment by lexicalunit** [comment]
Resolved by #23.

**Comment by lexicalunit** [comment]
@jbergstroem please give version 1.1.0 a try and see if it fixes this issue for you!

**Comment by jbergstroem** [comment]
> @lexicalunit said:
> @jbergstroem please give version 1.1.0 a try and see if it fixes this issue for you!

Just did, unfortunately not :( I'm on the 1.19 beta though, so I wouldn't lean on my feedback.

**Comment by lexicalunit** [comment]
Hrm interesting. I'm also on 1.19 beta and it seems to be working for me now. You should be able to tweak the package settings now to give a larger or smaller padding width. Maybe your theme needs a wider padding than mine. Try changing the new `Padding width in pixels to accommodate the window traffic lights` setting to see if that helps.

**Comment by jbergstroem** [comment]
> @lexicalunit said:
> Try changing the new `Padding width in pixels to accommodate the window traffic lights` setting to see if that helps.

Changing it to non-default worked indeed.

**Comment by jbergstroem** [comment]
Upon restart (with 1.2.1) I have to change this value in order for the margin to have effect.

**Comment by lexicalunit** [comment]
@jbergstroem do you have tree-view disabled by any chance?

**Comment by jbergstroem** [comment]
> @lexicalunit said:
> @jbergstroem do you have tree-view disabled by any chance?

No, right aligned.

**Comment by lexicalunit** [comment]
@jbergstroem Yeah, figured it out. I had some faulty logic in my code that, because of how I was testing things, didn't come up for me. Fixed in v1.2.2 🤞

**Comment by jbergstroem** [comment]
Just updated to 1.3.0 -- looks like I still have to update the value for it to have effect. Also, I now have a new right-border: 
<img width="889" alt="screen shot 2017-07-06 at 11 35 11 am" src="https://user-images.githubusercontent.com/176984/27919312-58191c24-623f-11e7-92e8-71466cf90788.png">

Want me to create a new issue?

**Comment by lexicalunit** [comment]
Those borders are intended:

![screen shot 2017-07-06 at 11 33 16 am](https://user-images.githubusercontent.com/1903876/27921910-ef292718-623e-11e7-922c-38960853eac3.png)

See how the bottom line below the traffic lights matches the bottom line of all the tabs. And left hand side border of the first tab now matches the left hand side border of other inactive tabs. I believe this is how things are intended to look with the Atom One Light/Dark Themes.

As for the not setting the padding at startup... it's weird. I had it working consistently the other day, but now it's not working consistently. I think there's a race condition in there somewhere. I'm investigating now.

**Comment by lexicalunit** [comment]
Tho... weird... upon closer inspection, your screenshot looks a bit different than mine. I was pretty sure you were using the One Light UI theme.

**Comment by lexicalunit** [comment]
Oohhhh! It's due to [your style sheet](https://github.com/lexicalunit/no-title-bar/issues/17#issuecomment-311396667).

Ah, it looks like you're specifically disabling the borders around tabs, whereas I'm expecting them to be there by default. Lemme whip up something you can add to your `styles.less` to give you the same effect, @jbergstroem!

**Comment by lexicalunit** [comment]
Hrm, well I figured out what the bottom border line is in your screenshot, @jbergstroem. It's the `box-shadow` for the `.tab-bar` element. You can get rid of that by adding one line to your `styles.less`:

```
[...]
.theme-one-light-ui {
  .tab-bar {
    font-size: 12px;
    box-shadow: none; // this line is added
    .tab {
      box-shadow: none;
      border: none;
    }
  }
[...]
```

**Comment by lexicalunit** [comment]
And to remove the vertical border to the right of the traffic lights you can add this to your `styles.less`:

```
.no-title-bar:not(.fullscreen):not(.hidden-title-bar) {
  .theme-one-light-ui, .theme-one-dark-ui {
    atom-panel-container.left + atom-workspace-axis.vertical {
      .pane:nth-child(1) .tab-bar {
        margin-left: 0 !important;
        .tab:nth-child(1):not(.active) {
          border-left: 0 !important;
        }
      }
    }
  }
}
```

I'm still working on the race condition that causes the traffic lights padding not to be set correctly at startup time...

**Comment by lexicalunit** [comment]
Ok, @jbergstroem I believe I found the race condition and worked around it. Fix is in release v1.3.1.

**Comment by jbergstroem** [comment]
@lexicalunit sorry; I usually disable my styles between testing but did not do so with 1.3.0. Apologies.

**Comment by jbergstroem** [comment]
Can confirm:
1. it now properly adds the margin to the tabs (!)
2. disabling my styles/adding your suggestion properly removes the border.

This is how my window looks, disabling all custom styles:
<img width="719" alt="screen shot 2017-07-07 at 9 54 06 am" src="https://user-images.githubusercontent.com/176984/27960751-69560298-62fa-11e7-9812-bfbeebdc5c8d.png">

**Comment by lexicalunit** [comment]
Oh interesting. I never tried testing with the Settings as the first tab. I wonder what's happening there... 🤔

**Comment by lexicalunit** [comment]
~@jbergstroem I wonder why your active tab doesn't have a bright left border like mine:~ Nevermind! See edit below.

<img width="293" alt="screen shot 2017-07-07 at 10 15 38 am" src="https://user-images.githubusercontent.com/1903876/27964276-4eebfaae-62fd-11e7-847b-1cc0d9008ac4.png">

The color seems to be dependent on the Style Theme. In my screenshot I've selected `Atom Dark`.

Edit: Ok I think maybe that's an artifact from switching themes because after a full Atom quit and restart it's gone now.

**Comment by lexicalunit** [comment]
Release v.1.3.3:

<img width="751" alt="screen shot 2017-07-07 at 10 21 34 am" src="https://user-images.githubusercontent.com/1903876/27964698-cc581d3c-62fe-11e7-8d9f-0ff85b8c8f9d.png">

**Comment by jbergstroem** [comment]
@lexicalunit looks very similar for me as well! great job. I guess the "last" piece would be the vertical alignment but that's another ordeal. I'll close this.
