### ISSUE TITLE
improve full screen

### ISSUE THREAD

**Issue by Kikobeats** [lexicalunit/no-title-bar#2]
love it this plugin; however, under fullscreen the tabs disappear.

Could be possible do something?

**Comment by lexicalunit** [comment]
I can look into it, yep! That definitely shouldn't be happening :(

**Comment by lexicalunit** [comment]
If v0.1.1 doesn't resolve this issue for you, @Kikobeats, please feel free to reopen with comments!

**Comment by Kikobeats** [comment]
you're the best! I'm going to check it

**Comment by mattapperson** [comment]
@lexicalunit seems there is a regression on this in 0.6.6?

I am on Atom 1.6

**Comment by lexicalunit** [comment]
Atom 1.6 is really old. Do you mean Atom 1.16? Either way it seems to be working for me on both 1.16 and the beta for 1.17. What setting are you using for the custom titlebar, @mattapperson? `custom`, `custom-inset`, or `hidden`?
