### ISSUE TITLE
Unable to re-order tabs

### ISSUE THREAD

**Issue by CedSharp** [lexicalunit/no-title-bar#25]
I am unable to re-order tabs using drag and drop.
More precisely, I can re-order non-editor tabs ( settings, package, etc ).
But any tabs for a text editor cannot be sorted ( you can drag it, but you can't drop it ).

![preview](https://camo.githubusercontent.com/d0cf0d50513dd5a9a3f3ec0e291bafb44c957ef0/687474703a2f2f692e696d6775722e636f6d2f466f773179796f2e676966)

**Comment by lexicalunit** [comment]
Hello @CedSharp, which version of Atom and `no-title-bar` are you currently running? Also what setting are you using for `Core > Title Bar`? It looks like maybe you're using `hidden`?

**Comment by lexicalunit** [comment]
Here's what I get using Atom 1.19.0-beta3 and `no-title-bar` v1.4.0 using the `custom` title bar setting. I also tried using the `hidden` title bar setting and got the same results.

![out](https://user-images.githubusercontent.com/1903876/28130744-690e066c-66fd-11e7-99e9-4a2b582eb692.gif)

Incidentally, how did you get such a nice screencast animated gif? I typically use [these instructions here](https://gist.github.com/dergachev/4627207) but yours is much cleaner looking while also being smaller in file size.
