### ISSUE TITLE
Make padding of all but top-left panel should be 0

### ISSUE THREAD

**Issue by kompot** [lexicalunit/no-title-bar#3]
<img width="1140" alt="screen shot 2016-12-24 at 18 14 04" src="https://cloud.githubusercontent.com/assets/231635/21468120/cd5b80fe-ca04-11e6-8260-b993b39f9d8c.png">

Right now there is padding left of 80px for every panel

`.platform-darwin atom-workspace atom-panel-container.left:empty + atom-workspace-axis.vertical .tab-bar`

**Comment by lexicalunit** [comment]
@kompot what UI theme are you using there? I can't recreate the issue with the themes I'm using.

**Comment by kompot** [comment]
It's One Dark
https://atom.io/themes/one-dark-ui

**Comment by lexicalunit** [comment]
If v0.1.2 doesn't resolve this issue for you, @kompot, please feel free to reopen with comments!

**Comment by kompot** [comment]
Great, thanks, working like a charm
