### ISSUE TITLE
Workaround element size not updating on resize

### ISSUE THREAD

**Issue by senki** [lexicalunit/no-title-bar#34]
Hi,

The element is overlapping with the tab-bar if you shrink the dock. Aso doesn't grow with the dock, but (at least for me) not a problem.

![workaround over tab](https://user-images.githubusercontent.com/459353/30798036-a2cf0a84-a20a-11e7-8163-585d32d6705a.png)

OS: Sierra 10.12.6
Atom: 1.20.1
no-title-bar: 1.11.2
theme: solarized-one-light-ui (which is basically just a colored atom/one-light-ui)

**Comment by lexicalunit** [comment]
Hrmmm weird. I’ll take a look!

**Comment by lexicalunit** [comment]
Ah, figured out what's happening. v1.11.3 should resolve the issue 🎉

**Comment by senki** [comment]
Confirmed, thanks!
