### ISSUE TITLE
Dragging to select changes in git change views moves window

### ISSUE THREAD

**Issue by alexcreid** [lexicalunit/no-title-bar#36]
Steps to reproduce in Atom 1.23.3:
- Open either the staged or unstated changes view provided by the bundled GitHub package.
- Click and drag over either the lines of the files in the change set, or the line numbers in the left margin. This should allow you to select lines to be staged, but instead the window is dragged.

**Comment by lexicalunit** [comment]
Thanks for reporting the issue! Fixed in v1.11.4.
