### ISSUE TITLE
tree-view resize

### ISSUE THREAD

**Issue by sergiokopplin** [lexicalunit/no-title-bar#7]
Hey, thanks for this awesome plugin!

I'm trying to resize my tree-view with the pointer, but it's not possible with the plugin enabled.
When i select the line-bar to resize, it moves the window (like the empty spaces on the readme).

Is that right?

Thanks! []'s

**Comment by lexicalunit** [comment]
Definitely a bug! I'll fix it in just a bit.

**Comment by lexicalunit** [comment]
@sergiokopplin this should be fixed now in v0.2.1. Thanks for the bug report!

**Comment by sergiokopplin** [comment]
thanks @lexicalunit! :)

**Comment by sergiokopplin** [comment]
tested and working! #fixed
